services:
  postgres:
    image: postgres:16
    container_name: postgres-jtech-todo
    restart: always
    ports:
      - "5442:5432"
    environment:
      POSTGRES_DB: jtech-todo-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
